# Generated by Django 5.0.2 on 2025-05-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True 

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostelListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Sharing'), ('triple', 'Triple Sharing')], max_length=20)),
                ('owner_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='hostel_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
