# Generated by Django 5.0.2 on 2025-05-31 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
    ]
